export const projects = [
  {
    id: "p1",
    title: "Evently",
    description: "Event management platform.",
    images: [
      "/evently/banner",
      "/evently/event_creation",
      "/evently/event",
      "/evently/account",
    ],
    reponame: "Evently",
    link: "https://event-one-beige.vercel.app/",
  },
  {
    id: "p2",
    title: "Agile",
    description: "Project management platform.",
    images: [
      "/agile/banner",
      "/agile/home",
      "/agile/projects",
      "/agile/backlog",
      "/agile/tasks",
      "/agile/submissions",
    ],
    reponame: "agile-project-manager",
    link: "https://agile-project-manager.vercel.app",
  },
  {
    id: "p3",
    title: "Social media app",
    description: "Social media app.",
    images: ["/social/banner"],
    reponame: "social-media",
    link: "https://agile-project-manager.vercel.app",
  },
  {
    id: "p4",
    title: "Library management system",
    description: "Simple library management system using cpp.",
    images: ["/library/banner"],
    reponame: "Library-management-system",
    link: "https://github.com/shuva7s/Library-management-system",
  },
];